import { TwitterMap } from "../twitter/initialize-twitter-map";
import { DEVPOOL_OWNER_NAME, DEVPOOL_REPO_NAME, GitHubIssue, GitHubIssueWithStateReason } from "./directory";
import { getIssueByLabel } from "./get-issue-by-label";
import { getRepoCredentials } from "./get-repo-credentials";
import { getRepositoryIssues } from "./get-repository-issues";
import { newDirectoryIssue } from "./new-directory-issue";
import { updateDirectoryIssue } from "./update-issue";

export async function syncPartnerRepoIssues({
  partnerRepoUrl,
  directoryIssues,
  twitterMap,
}: {
  partnerRepoUrl: string;
  directoryIssues: GitHubIssue[];
  twitterMap: TwitterMap;
}): Promise<GitHubIssue[]> {
  const [ownerName, repoName] = getRepoCredentials(partnerRepoUrl);
  let partnerRepoIssues = await getRepositoryIssues(ownerName, repoName);
  // Avoid self-recursion when Directory repo equals Partner repo by skipping
  // issues that were generated by the Directory sync itself. Those carry a
  // synthetic label in the form `id: <node_id>`.
  partnerRepoIssues = partnerRepoIssues.filter((issue) => {
    const labels = (issue.labels || []) as any[];
    return !labels.some((l) => typeof l?.name === "string" && l.name.startsWith("id: "));
  });
  const buffer: (GitHubIssue | null)[] = [];
  for (const partnerIssue of partnerRepoIssues) {
    // Cast to extended interface to access state_reason
    const issueWithReason = partnerIssue as GitHubIssueWithStateReason;
    
    // Skip issues that are closed as "not_planned" (unplanned)
    if (issueWithReason.state === "closed" && issueWithReason.state_reason === "not_planned") {
      continue;
    }
    
    // if the issue is open, then add it to the buffer
    if (partnerIssue.state === "open") {
      buffer.push(partnerIssue);
    }

    await createOrSync(partnerIssue);
  }
  return buffer.filter((issue) => issue !== null) as GitHubIssue[];

  async function createOrSync(partnerIssue: GitHubIssue) {
    const directoryIssue: GitHubIssue | null = getIssueByLabel(directoryIssues, `id: ${partnerIssue.node_id}`);

    // adding www creates a link to an issue that does not count as a mention
    // helps with preventing a mention in partner's repo especially during testing

    if (directoryIssue) {
      // if it exists in the Directory, then update it
      await updateDirectoryIssue({
        partnerIssue: partnerIssue,
        directoryIssue: directoryIssue,
      });
    } else {
      // Double-check right before creating to prevent race conditions
      const freshDirectoryIssues = await getRepositoryIssues(DEVPOOL_OWNER_NAME, DEVPOOL_REPO_NAME);
      const existingIssue = getIssueByLabel(freshDirectoryIssues, `id: ${partnerIssue.node_id}`);

      if (existingIssue) {
        console.log(`Issue already exists (found in fresh check): ${existingIssue.html_url} for partner issue: ${partnerIssue.html_url}`);
        // Update the existing issue instead of creating a duplicate
        await updateDirectoryIssue({
          partnerIssue: partnerIssue,
          directoryIssue: existingIssue,
        });
      } else {
        // if it doesn't exist in the Directory, then create it and update local cache
        const created = await newDirectoryIssue(partnerIssue, partnerRepoUrl, twitterMap);
        if (created) {
          directoryIssues.push(created);
        }
      }
    }

    return directoryIssue;
  }
}
